algolia/hn-search

app/assets/stylesheets/_home.css.sass
=> Force y-scroll to avoid window resize

app/assets/javascripts/app.js, app/assets/javascripts/application.js, app/assets/javascripts/attributedRelevance.js
=> added relevancy test

app/views/layouts/application.html.haml
Uses the proper search API key with the new endpoint and auth.
=> proper API key

app/views/layouts/application.html.haml
=> fix: make sure there's a notice for people with JS disabled

app/assets/javascripts/services.js, app/assets/templates/settings.html.haml
Should fix https://github.com/algolia/hn-search/issues/65 
Screenshots that show it working:
Before (currently on hn.algolia.com):
After (with this PR):
=> Adding an option in the UI to exclude an author's username in search.

app/assets/javascripts/app.js, app/assets/javascripts/controllers.js, db/schema.rb
Implements collection of front-end resource metrics - cc @asurak
=> [telemetry] - resource timings

app/assets/javascripts/app.js, app/assets/javascripts/controllers.js
=> Add engine processing time

app/assets/javascripts/controllers.js
Setup code to run A/B testing latency
=> [ab testing latency] - setup

app/assets/javascripts/app.js, package.json, yarn.lock
Log additional information from https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation whenever retries happen.
=> Request retry

app/assets/javascripts/services.js
Ensure the proximity is not impacting too much the story search by setting it to max 8.
=> Story search: set minPromixity to 8

app/models/item.rb
Remove ranking by relevancy score until we improve the weight on points
=> fix(ranking): remove relevancy score

app/assets/javascripts/controllers.js, app/assets/stylesheets/themes/default.css.sass, app/assets/templates/home.html.haml, package.json, yarn.lock
Adds ^ functionality with the help of the forked JS helper we are testing.
=> feat(retry-strategy): add loading indicator when slow network is detected and update js client

app/controllers/home_controller.rb, app/views/home/feed.atom.builder, config/schedule.rb
Fixes HN RSS fields. Should be valid now, I tested by manual input.
Ignore the relf="self", should be ok once ran in prod.
=> fix(rss): fix fields as per atom feed spec

app/javascript/components/SearchHeader/SearchHeader.scss, app/javascript/components/SearchResults/SearchResults.scss, app/javascript/components/SearchResults/SearchResults.tsx, app/javascript/components/Story/Story.scss, app/javascript/components/Story/Story.tsx, app/javascript/providers/SearchProvider.tsx, app/javascript/src/application.scss, app/javascript/src/variables.scss, app/models/item.rb, config/webpacker.yml
Makes the design much closer to new.ycombinator.com
=> style(hn): make this closer to news.ycombinator.com

app/javascript/components/Datepicker/Datepicker.tsx, app/javascript/components/Dropdown/Dropdown.tsx, app/javascript/components/Footer/Footer.tsx, app/javascript/components/Header/Header.tsx, app/javascript/components/Pagination/Pagination.tsx, app/javascript/components/SearchFilters/SearchFilters.tsx, app/javascript/components/SearchHeader/SearchHeader.tsx, app/javascript/components/SearchResults/NoResults.tsx, app/javascript/components/SearchResults/SearchResults.tsx, app/javascript/components/Sidebar/Sidebar.tsx, app/javascript/components/SocialShare/SocialShare.tsx, app/javascript/components/Story/Comments.tsx, app/javascript/components/Story/Story.tsx, app/javascript/components/Story/StoryImage.tsx, app/javascript/components/Tracker/Tracker.tsx, app/javascript/packs/application.tsx, app/javascript/views/About.tsx, app/javascript/views/Api.tsx, app/javascript/views/CoolApps.tsx, app/javascript/views/Help.tsx, app/javascript/views/Search.tsx, app/javascript/views/Settings.tsx, app/javascript/views/containers/Layout.tsx
Use function component and highlight URL
=> fix(react): use fc

app/javascript/components/SearchResults/NoResults.scss, app/javascript/providers/SearchSettings.ts, app/javascript/providers/__tests__/SearchSettings.test.ts, app/javascript/utils/telemetry.ts
Multiple filters were not working as they were not being correctly sent to the API
=> feat(filters): and filters

Gemfile, app/javascript/providers/SearchProvider.tsx, app/javascript/utils/telemetry.ts, app/models/item.rb, app/views/layouts/application.html.haml, config/deploy.rb, package.json, yarn.lock
Removed replicas and cleaned up the codebase a little bit
=> chore(cleanup): remove unnecessary replicas and cleanup codebase

app/javascript/components/SearchFilters/SearchFilters.scss, app/javascript/components/SearchHeader/SearchHeader.scss, app/javascript/components/Story/Story.scss, app/javascript/components/Story/Story.tsx, app/javascript/providers/Settings.ts, app/javascript/src/_normalize.scss, app/javascript/src/application.scss, app/javascript/src/experimental.scss, app/views/home/index.html.haml
Adjust styles as per feedback from HN
=> iteration(styles): adjust some styles as per feedback

app/javascript/components/Story/Story.tsx, app/javascript/providers/SearchSettings.ts, app/javascript/utils/parseHighlightedAttribute.ts
=> fix(xss): remove dangerouslySetInnerHTML

app/javascript/components/SearchResults/SearchResults.tsx, app/javascript/packs/application.tsx, app/javascript/providers/SearchProvider.tsx, package.json, yarn.lock
⚡️ Use the new IS client and add telemetry instrumentation ⚡️
=> feat(AlgoliaSearch): add v4 client

package-lock.json, package.json
* Update telemetry client to 0.1.5-rc.1 (appid detection)
=> Telemetry update: better appid detection

app/javascript/components/Dropdown/Dropdown.scss
=> fix(dropdown): readable color in browser dark mode

app/models/item.rb
Disabling searchableAttributes on VR.
=> exp(VirtualReplicas): disable searchableAttributes on VR

app/javascript/views/CoolApps.tsx
See here for more:
<https://news.ycombinator.com/item?id=26301600>
=> Add jstrieb/hackernews-button to "Cool Apps" list

app/javascript/views/About.tsx
=> fix(about): use direct URLs, not relative

Gemfile, Gemfile.lock, config/deploy.rb
Need to merge in order to deploy
=> chore: modifications for ubuntu 20.04
